name: Hashnode Blog Posts
on:
  schedule:
    # Runs every 7 days
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGPOSTS"
          feed_list: "https://neuronize.dev/rss.xml"
          template: |
            $newline <img src="$cover_image" alt="Cover Image" width="200" height="200" align="left">

            ## [$title]($url)

            $description

          commit_message: "recent posts section updated"
          gh_token: ${{ secrets.GH_TOKEN }}
